import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "@/contexts/cart-context";
import Footer from "@/components/footer/Footer";
import { AuthProvider } from "@/contexts/auth-context";
import { Toaster } from "@/components/ui/sonner"
import Header from "@/components/header/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-stone-50">
        <AuthProvider>
          <CartProvider>
            <Header />
            {children}
            <Toaster />
            <Footer />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
